# Generated by Django 3.2.2 on 2021-06-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='Watchlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlists',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='auctions.Listing'),
        ),
    ]
