# Generated by Django 3.2.2 on 2021-06-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210601_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlists',
            new_name='listings',
        ),
    ]
