# Generated by Django 3.2.2 on 2021-06-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210606_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_bid', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bidsListing', to='auctions.Bid'),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastBid', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
