# Generated by Django 3.2.2 on 2021-06-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210606_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='last_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bidsListing', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(),
        ),
    ]
