# Generated by Django 3.2.2 on 2021-06-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210609_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bidsListing', to='auctions.Bid'),
        ),
    ]
